CREATE TABLE "Client" (
	"ID"	INTEGER NOT NULL,
	"IDUser"	INTEGER NOT NULL DEFAULT 1,
	"FirstName"	TEXT NOT NULL,
	"LastName"	INTEGER NOT NULL,
	"PESEL"	TEXT NOT NULL UNIQUE,
	"Phone"	INTEGER,
	"Email"	INTEGER,
	"Active"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("IDUser") REFERENCES "User"("ID")
)