//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevExpressCreditDemo.credit
{

    public partial class Agreement : XPLiteObject
    {
        long fID;
        [Key]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>(nameof(ID), ref fID, value); }
        }
        Client fIDClient;
        [Indexed(Name = @"iIDClient_Agreement")]
        [Association(@"AgreementReferencesClient")]
        public Client IDClient
        {
            get { return fIDClient; }
            set { SetPropertyValue<Client>(nameof(IDClient), ref fIDClient, value); }
        }
        string fStartDate;
        [Size(SizeAttribute.Unlimited)]
        public string StartDate
        {
            get { return fStartDate; }
            set { SetPropertyValue<string>(nameof(StartDate), ref fStartDate, value); }
        }
        string fEndDate;
        [Size(SizeAttribute.Unlimited)]
        public string EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<string>(nameof(EndDate), ref fEndDate, value); }
        }
        double fAmount;
        public double Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<double>(nameof(Amount), ref fAmount, value); }
        }
        byte[] fAttachment;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Attachment
        {
            get { return fAttachment; }
            set { SetPropertyValue<byte[]>(nameof(Attachment), ref fAttachment, value); }
        }
        long fActive;
        public long Active
        {
            get { return fActive; }
            set { SetPropertyValue<long>(nameof(Active), ref fActive, value); }
        }
        long fPercent;
        public long Percent
        {
            get { return fPercent; }
            set { SetPropertyValue<long>(nameof(Percent), ref fPercent, value); }
        }
        long fIinstallmentCount;
        public long IinstallmentCount
        {
            get { return fIinstallmentCount; }
            set { SetPropertyValue<long>(nameof(IinstallmentCount), ref fIinstallmentCount, value); }
        }
        double fInstallment;
        public double Installment
        {
            get { return fInstallment; }
            set { SetPropertyValue<double>(nameof(Installment), ref fInstallment, value); }
        }
        long fDayOfPement;
        public long DayOfPement
        {
            get { return fDayOfPement; }
            set { SetPropertyValue<long>(nameof(DayOfPement), ref fDayOfPement, value); }
        }
        [Association(@"RepaymentsReferencesAgreement")]
        public XPCollection<Repayments> RepaymentsCollection { get { return GetCollection<Repayments>(nameof(RepaymentsCollection)); } }

        /// <summary>
        /// Data pierwszej wpłaty
        /// </summary>
        public DateTime DateStartToPaid
        {
            get
            {
                DateTime dtAgrStart = DateTime.Parse(fStartDate).AddMonths(1);
                return new DateTime(dtAgrStart.Year, dtAgrStart.Month, (int)fDayOfPement);
            }
        }

        /// <summary>
        /// Data ostatniej wpłaty
        /// </summary>
        public DateTime DateEndToPaid
        {
            get
            {
                DateTime dtAgrStart = DateTime.Parse(fEndDate);
                return new DateTime(dtAgrStart.Year, dtAgrStart.Month, (int)fDayOfPement);
            }
        }

        public double PercentAsDouble { get { return (double)fPercent / 100; } }
    }
}


