//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevExpressCreditDemo.credit
{

    public partial class Agreement : XPLiteObject
    {
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>(nameof(ID), ref fID, value); }
        }
        Client fIDClient;
        [Association(@"AgreementReferencesClient")]
        public Client IDClient
        {
            get { return fIDClient; }
            set { SetPropertyValue<Client>(nameof(IDClient), ref fIDClient, value); }
        }
        string fStartDate;
        [Size(SizeAttribute.Unlimited)]
        public string StartDate
        {
            get { return fStartDate; }
            set { SetPropertyValue<string>(nameof(StartDate), ref fStartDate, value); }
        }
        string fEndDate;
        [Size(SizeAttribute.Unlimited)]
        public string EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<string>(nameof(EndDate), ref fEndDate, value); }
        }
        double fAmount;
        public double Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<double>(nameof(Amount), ref fAmount, value); }
        }
        byte[] fAttachment;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Attachment
        {
            get { return fAttachment; }
            set { SetPropertyValue<byte[]>(nameof(Attachment), ref fAttachment, value); }
        }
        long fActive;
        public long Active
        {
            get { return fActive; }
            set { SetPropertyValue<long>(nameof(Active), ref fActive, value); }
        }
        [Association(@"RepaymentsReferencesAgreement")]
        public XPCollection<Repayments> RepaymentsCollection { get { return GetCollection<Repayments>(nameof(RepaymentsCollection)); } }
    }

}
