//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevExpressCreditDemo.credit
{

    public partial class Client : XPLiteObject
    {
        long fID;
        [Key]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>(nameof(ID), ref fID, value); }
        }
        string fFirstName;
        [Size(SizeAttribute.Unlimited)]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fLastName;
        [Size(SizeAttribute.Unlimited)]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        string fPESEL;
        [Indexed(Name = @"sqlite_autoindex_Client_1", Unique = true)]
        [Size(SizeAttribute.Unlimited)]
        public string PESEL
        {
            get { return fPESEL; }
            set { SetPropertyValue<string>(nameof(PESEL), ref fPESEL, value); }
        }
        long fActive;
        public long Active
        {
            get { return fActive; }
            set { SetPropertyValue<long>(nameof(Active), ref fActive, value); }
        }
        [Association(@"AgreementReferencesClient")]
        public XPCollection<Agreement> Agreements { get { return GetCollection<Agreement>(nameof(Agreements)); } }
    }

}
