//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevExpressCreditDemo.credit
{

    public partial class User : XPLiteObject
    {
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>(nameof(ID), ref fID, value); }
        }
        SystemRole fIDRole;
        [Association(@"UserReferencesSystemRole")]
        public SystemRole IDRole
        {
            get { return fIDRole; }
            set { SetPropertyValue<SystemRole>(nameof(IDRole), ref fIDRole, value); }
        }
        string fFirstName;
        [Size(SizeAttribute.Unlimited)]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fLastName;
        [Size(SizeAttribute.Unlimited)]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        string fLogin;
        [Indexed(Name = @"sqlite_autoindex_User_1", Unique = true)]
        [Size(SizeAttribute.Unlimited)]
        public string Login
        {
            get { return fLogin; }
            set { SetPropertyValue<string>(nameof(Login), ref fLogin, value); }
        }
        string fHashPass;
        [Size(SizeAttribute.Unlimited)]
        public string HashPass
        {
            get { return fHashPass; }
            set { SetPropertyValue<string>(nameof(HashPass), ref fHashPass, value); }
        }
        [Association(@"ClientReferencesUser")]
        public XPCollection<Client> Clients { get { return GetCollection<Client>(nameof(Clients)); } }
        [Association(@"AgreementReferencesUser")]
        public XPCollection<Agreement> Agreements { get { return GetCollection<Agreement>(nameof(Agreements)); } }
    }

}
