//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevExpressCreditDemo.credit
{

    public partial class User : XPLiteObject
    {
        long fID;
        [Key]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>(nameof(ID), ref fID, value); }
        }
        string fName;
        [Size(SizeAttribute.Unlimited)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fFullName;
        [Size(SizeAttribute.Unlimited)]
        public string FullName
        {
            get { return fFullName; }
            set { SetPropertyValue<string>(nameof(FullName), ref fFullName, value); }
        }
        string fLogin;
        [Indexed(Name = @"sqlite_autoindex_User_1", Unique = true)]
        [Size(SizeAttribute.Unlimited)]
        public string Login
        {
            get { return fLogin; }
            set { SetPropertyValue<string>(nameof(Login), ref fLogin, value); }
        }
        string fHashPass;
        [Size(SizeAttribute.Unlimited)]
        public string HashPass
        {
            get { return fHashPass; }
            set { SetPropertyValue<string>(nameof(HashPass), ref fHashPass, value); }
        }
    }

}
